### ISSUE TITLE
ERROR while running annotation step with vep

### ISSUE THREAD

**Issue by FrancisNietzsche** [nf-core/sarek#1139]
### Description of the bug

So I chose to manually downloaded the vep_cache files and use dbNSFP plugin for the annotation, but the annotating step terminated with an error exit status. And I cannot find out whether it was because the vep cache file was not correctly directed or anything else.

### Command used and terminal output

```console
Nextflow command
nextflow run /dssg/home/acct-medlhp/medlhp-wzc/software/sarek --step annotate --tools vep --input //dssg/home/acct-medlhp/medlhp-wzc/project/sarek_jobs/results/0518-2/csv/variantcalled.csv --outdir /dssg/home/acct-medlhp/medlhp-wzc/project/sarek_jobs/results/anno_test --vep_dbnsfp --vep_cache /dssg/home/acct-medlhp/medlhp-wzc/cache_files/homo_sapiens/106_GRCh38 --igenomes_base /dssg/home/acct-medlhp/medlhp-wzc/references --genome GATK.GRCh38 -profile singularity
```

### Relevant files

[26161760.txt](https://github.com/nf-core/sarek/files/11903534/26161760.txt)

**Comment by maxulysse** [comment]
try with `--vep_cache /dssg/home/acct-medlhp/medlhp-wzc/cache_files`

**Comment by FriederikeHanssen** [comment]
@FrancisNietzsche Did this help?

**Comment by FrancisNietzsche** [comment]
Yes, it did help, thanks so much!

**Comment by chumawinnie** [comment]
**Title:** VEP Annotation Step Not Executed in Sarek Pipeline Despite Successful Completion

**Description:**
Hi nf-core Sarek team,

I recently ran a whole exome sequencing (WES) analysis using the Sarek pipeline. While the pipeline completed successfully without any errors, the final VEP annotation step did not execute or produce the expected output. I couldn't find any VEP-related files in the output directory, and there was no indication of the VEP process in the log files either.

**Command Used:**
```bash
nextflow run nf-core/sarek -profile docker \
  --input sample-merge-sheet.csv \
  --outdir /home/obiorach/test-work-sarek/Merged-WES-Results \
  --genome hg19 \
  --dbsnp /home/obiorach/whole-Exon-single-seq/ref-genome/known_sites.vcf/dbsnp_138.hg19.vcf.gz \
  --known_indels /home/obiorach/whole-Exon-single-seq/ref-genome/known_indels.vcf/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /home/obiorach/whole-Exon-single-seq/ref-genome/exom_targets.bed/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka \
  --pon /home/obiorach/whole-Exon-single-seq/ref-genome/panel-of-normal/updated_Mutect2-exome-panel_vcf.vcf.gz \
  --germline_resource /home/obiorach/whole-Exon-single-seq/ref-genome/germline-resource/renamed_gnomad.vcf.gz \
  --vep_cache /home/obiorach/datasets/auxiliary_files_and_databases/VEP_cache/homo_sapiens \
  --vep_species homo_sapiens \
  --vep_genome GRCh37 \
  --vep_cache_version 106 \
  -c custom.config
```

**Screenshots:**

1. **Directory Listing of Output Files:**

 
![Screenshot from 2024-08-16 10-40-42](https://github.com/user-attachments/assets/649d7c69-e8ff-4dfa-9b79-832d4efd4cc2)

   *In the screenshot above, the expected VEP annotation files are missing.*

2. **Pipeline Execution Summary:**

  
![Screenshot from 2024-08-16 10-32-55](https://github.com/user-attachments/assets/fdc2113a-b4d0-48a3-8a36-dec0dec516cd)

   *The pipeline summary shows that all processes completed successfully, but there's no mention of VEP.*


- Genome: hg19
- VEP cache version: 106


**Steps Taken to Troubleshoot:**
- Verified the paths to the VEP cache and resources.
- Checked the configuration file for any misconfigurations.
- Reviewed the logs, but no VEP process is mentioned.

**Expected Behavior:**
The VEP annotation step should have been executed, producing annotated VCF files as output.

**Actual Behavior:**
The VEP annotation step appears to be skipped or not executed, with no output files generated and no logs indicating its execution.

Please let me know if there's anything I might have missed or if additional information is needed to resolve this issue.

Thank you for your support!

**Comment by FriederikeHanssen** [comment]
Hey! you need to add `vep` to the `--tools ` command you are using `  --tools mutect2,strelka,vep`

**Comment by chumawinnie** [comment]
Hallo Friederike, danke, ich werde es ausprobieren.

**Comment by chumawinnie** [comment]
### Issue with VEP Annotation in Offline Mode - `--hgvs` Disabled Due to Missing FASTA File

Hi nf-core/sarek community,

I recently encountered an issue while running the VEP annotation step in my nf-core/sarek pipeline. Below is the initial code I used to run the pipeline:

```bash
nextflow run nf-core/sarek -profile docker \
  --input samplesheet.csv \
  --outdir /home/obiorach/test-work-sarek/WES-test-result \
  --genome hg19 \
  --dbsnp /home/obiorach/whole-Exon-single-seq/ref-genome/known_sites.vcf/dbsnp_138.hg19.vcf.gz \
  --known_indels /home/obiorach/whole-Exon-single-seq/ref-genome/known_indels.vcf/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /home/obiorach/whole-Exon-single-seq/ref-genome/exom_targets.bed/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka,vep \
  --pon /home/obiorach/whole-Exon-single-seq/ref-genome/panel-of-normal/updated_Mutect2-exome-panel_vcf.vcf.gz \
  --germline_resource /home/obiorach/whole-Exon-single-seq/ref-genome/germline-resource/renamed_gnomad.vcf.gz \
  --vep_cache /home/obiorach/datasets/auxiliary_files_and_databases/VEP_cache \
  --vep_species homo_sapiens \
  --vep_genome GRCh37 \
  --vep_cache_version 106 \
  -c custom.config \
  -resume
```

During the VEP annotation step, I executed the following command:

```bash
vep \
  -i Normal.strelka.variants.vcf.gz \
  -o Normal.strelka.variants_VEP.ann.vcf.gz \
  --stats_file Normal.strelka.variants_VEP.ann.summary.html \
  --vcf --everything --filter_common --per_gene --total_length --offline --format vcf \
  --compress_output bgzip \
  --assembly GRCh37 \
  --species homo_sapiens \
  --cache \
  --cache_version 106 \
  --dir_cache ${PWD}/VEP_cache \
  --fork 6
```

However, I received the following message:

```
2024-08-18 21:45:32 - INFO: Disabling --hgvs; using --offline and no FASTA file found
```

It seems that the `--hgvs` option is being disabled because I’m running VEP in offline mode without providing a reference FASTA file. This behavior was unexpected, and I’m not sure how critical it is for my downstream analysis.

### My Questions:
1. **Is providing a FASTA file mandatory for accurate VEP annotations in offline mode, specifically when `--hgvs` is needed?**
2. **What are the potential impacts of not having HGVS annotations on the final output?**
3. **Is there a recommended solution for this within the nf-core/sarek workflow, or do I need to manually include a FASTA file in the VEP command?**

I’m using GRCh37 as my reference genome and have the VEP cache properly set up. Any guidance or suggestions on how to resolve this issue or any workarounds that might be available would be greatly appreciated.

Thank you for your help!

Best regards,  
winner

**Comment by chumawinnie** [comment]
---

### Issue: VEP Annotation Stuck at 25% for 3 Days in WES Analysis

#### Description:
I am experiencing an issue with the Sarek pipeline during Whole Exome Sequencing (WES) analysis. The pipeline is getting stuck at 25% progress during the VEP annotation step. This has been happening for over three days without any further progress. I've attached a screenshot showing the pipeline's status.
![Screenshot from 2024-08-21 09-20-49](https://github.com/user-attachments/assets/34d1c56e-7bd4-4b70-892c-2241a9db3d1d)


#### Pipeline Command:
```bash
nextflow run nf-core/sarek -profile docker \
  --input samplesheet.csv \
  --outdir /home/obiorach/test-work-sarek/WES-test-result \
  --genome hg19 \
  --dbsnp /home/obiorach/whole-Exon-single-seq/ref-genome/known_sites.vcf/dbsnp_138.hg19.vcf.gz \
  --known_indels /home/obiorach/whole-Exon-single-seq/ref-genome/known_indels.vcf/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /home/obiorach/whole-Exon-single-seq/ref-genome/exom_targets.bed/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka,vep \
  --pon /home/obiorach/whole-Exon-single-seq/ref-genome/panel-of-normal/updated_Mutect2-exome-panel_vcf.vcf.gz \
  --germline_resource /home/obiorach/whole-Exon-single-seq/ref-genome/germline-resource/renamed_gnomad.vcf.gz \
  --vep_cache /home/obiorach/datasets/auxiliary_files_and_databases/VEP_cache \
  --vep_species homo_sapiens \
  --vep_genome GRCh37 \
  --vep_cache_version 106 \
  -c custom.config \
  -resume
```

#### Config File:
```groovy
process {
    // General settings
    withName: ".*" {
        time = 72.h
    }

    // Specific settings for Mutect2
    withName: 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_MUTECT2:MUTECT2_PAIRED' {
        memory = 30.GB
        cpus = 20
        time = 72.h
    }
}
```

#### Observations:
- **CPU Usage**: The CPU usage is minimal, often showing 0.1% or 0.0% while the pipeline is stuck.
- **Custom VEP Annotation**: Running the generated VCF file through a custom python VEP annotation script only took 2 minutes, suggesting the issue might be specific to the Sarek pipeline.
- **Screenshot**: [Screenshot attached showing pipeline status]

#### Steps Taken:
- I've verified the config file for errors and have not found any issues.
- I have checked the VEP cache location and version, and they seem correct.

#### Request for Help:
- Has anyone else experienced this issue with VEP annotation in the Sarek pipeline?
- Are there any known bugs or workarounds for speeding up the VEP annotation step?
- Any advice on how to debug or resolve this issue would be greatly appreciated.

Thank you in advance for your help!

---

**Comment by FriederikeHanssen** [comment]
Definitely not normal. Is being "stuck" reproducible? Does it run through if you resume? I notice you are using a slightly older cache. I think from you previous comment I remember you being on sarek version 3.4.2? For you local run did you use the same vep container and cache version as the combination you are running here?

**Comment by chumawinnie** [comment]
> Definitely not normal. Is being "stuck" reproducible? Does it run through if you resume? I notice you are using a slightly older cache. I think from you previous comment I remember you being on sarek version 3.4.2? For you local run did you use the same vep container and cache version as the combination you are running here?

Thank you for your prompt response.

- **Is being "stuck" reproducible?**  
  Yes, the issue is reproducible. Every time I run the pipeline, it gets stuck at the same point during the VEP annotation step, and it consistently halts at 25%.

- **Does it run through if you resume?**  
  Unfortunately, resuming the pipeline doesn't help. The process resumes but again gets stuck at the same 25% progress.

- **VEP Cache and Sarek Version:**

  Yes, I am using Sarek  older version The VEP cache version is 106, which I realize might be slightly outdated, however the analysis required i should use that. 

  For my local run using a custom Python script for annotation, I did not use a container. However, I used the same VEP cache version (106) as in the Sarek pipeline. The annotation completed in less than 2 minutes locally, which is why I'm confused about why the pipeline is stuck.



Would you recommend updating the VEP cache or the Sarek version? Or is there anything else I might try to resolve this issue?

Thanks again for your assistance.

**Comment by chumawinnie** [comment]
Hello Friederike, the issue has been resolved. I simply updated the VEP cache to the latest version, and everything worked without any further problems. Thanks for your help and quick response.
![image](https://github.com/user-attachments/assets/fa1c2450-cfc4-40c2-b6b8-07709cb77754)

**Comment by FriederikeHanssen** [comment]
odd, but glad it worked

**Comment by kobeikegami** [comment]
I am having a similar issue: VEP doesn't seem to be annotating my vcf files, looking at my multiqc I can tell VEP is producing stats on my file. here's my command and a relevant snippet from the log file and command.err file:
command:
nextflow run nf-core/sarek -r 3.4.0 -profile  singularity -resume \
 --input /lustre/home/nej_lab/fastq/human/muscle/whole_exome/run5/samplesheet1.csv \
 --outdir /lustre/home/nej_lab/pro_seq_data/wes/test \
 --wes --intervals /lustre/home/nej_lab/genomes/wes_beds/agilent_beds/S33266340_Regions_no_head.bed --tools haplotypecaller,vep \
 --only_paired_variant_calling --vep_cache /lustre/home/nej_lab/vep_caches \
 --vep_species homo_sapiens --vep_genome GRCh38 --vep_cache_version 110

log:
Oct-25 17:20:31.041 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 88; name: NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_ENSEMBLVEP:ENSEMBLVEP_VEP (S7); status: RUNNING; exit: -; error: -; workDir: /lustre/home/nej_lab/fastq/human/muscle/whole_exome/run5/work/a8/41ba22cb518a01d54cffcaffbf43c5]
Oct-25 17:23:35.803 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 88; name: NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_ENSEMBLVEP:ENSEMBLVEP_VEP (S7); status: COMPLETED; exit: 0; error: -; workDir: /lustre/home/nej_lab/fastq/human/muscle/whole_exome/run5/work/a8/41ba22cb518a01d54cffcaffbf43c5]
Oct-25 17:23:35.996 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_ENSEMBLVEP:ENSEMBLVEP_VEP > Skipping output binding because one or more optional files are missing: fileoutparam<1:1>
Oct-25 17:23:35.997 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_ENSEMBLVEP:ENSEMBLVEP_VEP > Skipping output binding because one or more optional files are missing: fileoutparam<2:1>

 command.log:
INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
Smartmatch is experimental at /usr/local/share/ensembl-vep-110.0-0/modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm line 472.
2024-10-25 17:16:25 - INFO: Disabling --hgvs; using --offline and no FASTA file found

Any advice would be greatly appreciated!
