### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by sxv** [nf-core/sarek#1235]
### Description of the bug

Hi,

Running sarek locally on a disk with 3TB available, however the total space used by the pipeline (mostly the work/ directory) exceeds this and the pipeline fails.

Questions:

1) is there a way to prevent this from happening other than by breaking down the batch and running the pipeline on smaller subsets of samples?

2) When I resume the pipeline (with --resume), should I delete the contents of work/ before resuming?

Thanks,
Sujay

**Comment by FriederikeHanssen** [comment]
There are a few tricks to reduce it further at the expense of runtime. You can turn off read splitting for mapping with `--split_fastq 0` and you can reduce or turn of scatter/gathering for BQSR and variantcalling by increasing `--nucleotides_per_second` . If you use the default interval file for example a value of i think `5000000` for sure turns of all scatter/gathering and processes all intervals in one job. 

Otherwise breaking it down into batches is a good idea. And turning of all tools you are not interested in. 

I wouldn't remove the `work` directory as resume won't work anymore. However, if you `resume` a lot then `work` will get bigger. alternatively you could also take a look at the `--step` parameter, i.e. if you are repeatedly just rerunning variantcalling because you are adjusting settings there. 
I tend to break preprocessing and variantcalling up when I have big cohorts. Preprocessing is pretty standardized, and the variety comes in later.

**Comment by sxv** [comment]
Thanks, that makes sense. Would it be possible to break down the batch (by subsetting the input.csv file) and then using the --resume flag?
