### ISSUE TITLE
mispelled field in the samplesheet does not raise an issue

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#1504]
### Description of the bug

Using `satus` instead of `status` does not fail.
That could be problematic when one expect status to be used.

@mirpedrol any idea on how to catch that?

> Issue reported by [Ist4lri](https://github.com/Ist4lri)

**Comment by maxulysse** [comment]
@Ist4lri actually I just tried that, and I noticed this warning:

```
WARN: Samplesheet warnings:
	The samplesheet contains following unchecked field(s): [satus]
```

Did you noticed it in your logs?

**Comment by Ist4lri** [comment]
I'm back :)
In my HPC log file I have this line : 
```
WARN: Samplesheet warnings:
        The samplesheet contains following unchecked field(s): [satus]
```
In the .nextflow.log file, il have this : 
```
May-06 16:51:52.558 [main] WARN  n.validation.SamplesheetConverter - Samplesheet warnings:
        The samplesheet contains following unchecked field(s): [satus]
```

So, the plugin is curretly runnig well :) 

False alert, everything alright for this warning

**Comment by mirpedrol** [comment]
additional columns tend to be valid on a sample sheet, that's why we can't throw an error by default. One option would be to add a parameter to make those fail, similar to the [`failUnrecognisedParams`](https://nextflow-io.github.io/nf-schema/latest/configuration/configuration/#failunrecognisedparams) we have for pipeline params.
