### ISSUE TITLE
Parallelization of BaseRecalibrator

### ISSUE THREAD

**Issue by samkleeman1** [nf-core/sarek#341]
Hi,

I am using this pipeline to run exome sequencing analysis on about 1000 samples (tumor-normal pairs) on our cluster (SGE). We are finding that for the steps BaseRecalibrator and ApplyBQSR, the pipeline is splitting the genome into tiny chunks, each taking about 30 seconds to run. However, with SGE job management, it cannot keep up with this rate of job requests and so jobs often spend longer waiting to be started than actually running. Is there a way to modify the size of genome chunk being used? My command is copied below.

Kind regards,

Dr Sam Kleeman
PhD Student
Cold Spring Harbor Laboratory, NY 

`nextflow run -resume nf-core/sarek -profile singularity -c /mnt/grid/janowitz/home/skleeman/nextflow/nextflow.config -r 2.6.1 --tools 'Strelka, Manta, MSIsensor, SnpEff' --genome GRCh38  --target_bed /mnt/grid/janowitz/home/references/exome_regions_padded.bed --skip_qc all --outdir /mnt/grid/janowitz/rdata_norepl/pan_immuno/output/dna --igenomes_base /mnt/grid/janowitz/home/references/human_dna/references/references --step prepare_recalibration`

**Comment by MaxUlysse** [comment]
I see so this parallelization is mainly controlled by the intervals file: https://nf-co.re/sarek/2.7/parameters#intervals
For exome sequencing, especially is the jobs are that fast, you might want to try the `--no_intervals` params (cf: https://nf-co.re/sarek/2.7/parameters#no_intervals) that disable the usage of intervals.
Otherwise, you can make your own intervals file, and try to have something like just one chromosome per intervals.
