### ISSUE TITLE
adaptation for custom read names (specifically MGISEQ)

### ISSUE THREAD

**Issue by raimondsre** [nf-core/sarek#395]
I'm attempting to call variants on MGISEQ .fq, although very similar to Illumina, there are some differences, for example this is read header for mgiseq "@V300082373L1C001R0061260954/1".

May i ask what adaptations should be made for a successful execution, if any?

**Comment by maxulysse** [comment]
@raimondsre Did you manage to figure out a solution for that?

**Comment by raimondsre** [comment]
I did not get a definitive answer, mainly concerning effect on quality score recalibration step. I will try to compare with 1000G Illumina sample.

**Comment by lassefolkersen** [comment]
I have run MGISEQ samples from GiAB on Sarek with haplotypecaller. I left the PL filed as ILLUMINA, because [GATK](https://gatk.broadinstitute.org/hc/en-us/articles/360035890671-Read-groups) documentation says MGI is not possible. Then I took care to specify LANE in the sample.csv according to each of the separate fastq-pairs available from GiAB, and patient and sample obviously as unique for the relevant GiAB samples.

As far as I understand BQSR this is sufficient and according to documentation. This conclusion is supported by the very good precision and recall rates that was found. 

```
                    | SNP recall | SNP precision | INDEL recall | INDEL precision 
MGISEQ_HG002_40x    | 0.99219    | 0.991396      | 0.992905     | 0.997014 
```

I hope this helps @raimondsre

**Comment by maxulysse** [comment]
I'm closing the issue, as I feel @lassefolkersen gave a good solution.
@raimondsre feel free to comment or reopen if needed
