### ISSUE TITLE
Update Sarek docs

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#402]
In general the docs need to be overhauled, including:

- [x] #502
- [x] #503
- [x] #504

**Comment by jfy133** [comment]
I have no idea why I was self-assigned there :sweat_smile:

**Comment by maxulysse** [comment]
You like us this much <3

**Comment by FriederikeHanssen** [comment]
Tube map called you, James ;)

**Comment by gorgitko** [comment]
Hi, just a small note. For me it's not clearly evident in which order to run the individual `--step` parameters. E.g. first I run `--step mapping` and then all the subsequent steps till `annotate`? Or I can run `variant_calling` and `annotate` right after `mapping`? Thanks for the clarification :slightly_smiling_face:

PS maybe I am just misreading the docs, otherwise it would be good to update them accordingly since I am probably not alone having this misunderstanding.

**Comment by FriederikeHanssen** [comment]
@gorgitko thanks for the feedback. I will surely try to make this more clear in the upcoming rewrite :)
