### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CSynodinos** [nf-core/sarek#519]
Hello,
I am trying to run the pipeline with my own dataset but I get the following error:

Unexpected error [UnsupportedOperationException]

 -- Check script '/Users/christossynodinos/.nextflow/assets/nf-core/sarek/main.nf' at line: 211 or see '.nextflow.log' file for more details

Command line: nextflow run nf-core/sarek --input sarek_input.tsv -profile docker

- Hardware: Desktop
- OS: MacOS
- Nextflow version: 21.04.0
- Engine: Docker
- version: 4.5.0

The dataset comes from an Illumina MiSeq machine.

[nextflow.log](https://github.com/nf-core/sarek/files/8426577/nextflow.log)

I was able to run the test dataset using docker.

**Comment by maxulysse** [comment]
I'd recommend downloading the AWS iGenomes reference genome separately
It seems that the issue is coming from an error when handling the download of one of the files in the s3 bucket

**Comment by CSynodinos** [comment]
I was able to run it with the AWS iGenomes reference in the end. Nevertheless, I have downloaded the GRCh38 genomes in my local system. How would you recommend passing the local paths to the pipeline? Using --igenomes_base or through a custom config file?

**Comment by maxulysse** [comment]
I'd recommend using `--igenomes_base` in a custom config file, it's much simpler, and easy to reuse the same config file for another run, or even another pipeline, or if you want to, you can even go for adding it to our [nf-core/configs](https://github.com/nf-core/configs/)
Happy to know that problem is now solved for you.
Don't hesitate if you have any more issues, or need any clarification

**Comment by CSynodinos** [comment]
Excellent, thank you for your recommendations and you help!
