### ISSUE TITLE
[BUG] VEP and SnpEff cache cannot be defined in nextflow.config

### ISSUE THREAD

**Issue by lassefolkersen** [nf-core/sarek#634]
## Description of the bug

For Sarek 3.0, dev-branch, wWhen including the following in a config file
```
params{
   vep_cache = 's3://somewhere'
}
```
The expected behaviour is to _not_ pull the  VEP-container, but instead use a cache. However it does pull the (quite big) container. So the bug may show as a `CannotPullContainerError: write /var/lib/docker/tmp/GetImageBlob370078793: no space left on device` error, especially when running with awsbatch. The choice is [made on this line](https://github.com/nf-core/sarek/blob/42b1860da9e0e4229b434c27aa6c1427510d0b99/conf/modules.config#L1160), where `params.vep_cache` is always empty. This can be bypassed by instead providing `--vep_cache` as command line switch, which is why the bug is marked as low-priority and postponed for backlog.

## Additional context

In [this slack thread](https://nfcore.slack.com/archives/C02MDBZAYJK/p1657633991763159), the sarek3.0 channel of nf-core slack. Possibly related to [this issue.](https://github.com/nextflow-io/nextflow/issues/2662)

**Comment by maxulysse** [comment]
Since we can't see the Slack thread as it's a private one, I'll recapitulate the problem, and hopefully give some solutions for now:
We can't access from the modules.configs params defined in a custom config files, due to https://github.com/nextflow-io/nextflow/issues/2662
Solution is either to specify from command line, edit the nextflow.config, or in an institutional profile.
I'm closing the issue as `won't fix` for now, but it's because it's closed that it's forgotten ;-)
