### ISSUE TITLE
MultiQC doesn't show BCFTools/VCFTools plots for WGS

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#779]
### Description of the bug

as stated in the title. I believe we might need to use the interval bed files afterall, or see if it is a mqc issue.

**Comment by SusiJo** [comment]
As it turns out, there was a little issue with MultiQC that would show empty depth distribution plots in the section `bcftools stats`, but that should be solved with using the latest changes in MultiQC. However, the bcftools variant depths cannot be reported for some variant callers like Strelka2 because this caller does not report the INFO/DP field which would be required for extracting the variant depth distribution by bcftools stats.
