### ISSUE TITLE
GroupKey Logic for multiple lanes with different sizes based on line splitting

### ISSUE THREAD

**Issue by achristofferson-bbi** [nf-core/sarek#853]
Will this logic work for samples that have been run across multiple lanes and split_fastq turned on?
If BAM_MARKDUPLICATES_SPARK is the next step and 1 lane of fastqs was split into 2 and the other was split into 3 then BAM_MARKDUPLICATES_SPARK  won't run at all or it will only run with 4 out of the 5 aligned bams.

Am I missing something?

https://github.com/nf-core/sarek/blob/0b7f0e2b6f0be7053838ba1884b2eb03e9f83f9e/workflows/sarek.nf#L500-L522

**Comment by maxulysse** [comment]
@achristofferson-bbi we reworked that part now, hopefully it should be clearer now

**Comment by FriederikeHanssen** [comment]
re-opening this issue. as discussed on slack the updates in #896 don't actually address this. 

I believe the fix would be to add instead of multiply, but I am not quite sure yet how we can do this from a technical perspective, since we won't have access to all meta.maps in the channel mapping in parallel...... One workaround could be to force the user to supply total number of lane (or compute it on samplesheet parsing), then at least we are ride of one variable part. However, even then I don't see a straight forward way right now to make sure to group them properly without causing any form of bottleneck, which here would not be acceptable.

**Comment by FriederikeHanssen** [comment]
🦆 moment: maybe multiple levels of grouping can get us there

**Comment by maxulysse** [comment]
@FriederikeHanssen do you think this is now finally fixed?

**Comment by FriederikeHanssen** [comment]
Fixed in th elinked PR
