### ISSUE TITLE
Collection of issues regarding joining on metamaps 

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#975]
### Description of feature

We have experienced several issues with respect to how we use meta maps. Some of them should hipefully be fixed on dev,
however there is still a few remaining that seem related:

@BrunoGrandePhD found that FILTERMUTECTCALLS is only run sporadically. Can confirm this, on the same input data sometimes it is run and sometimes not. `failOnDuplicate` and `failOnMismatch` were added to get better error messages and see what is happening. so far we know that the `join` operator then fails due to mismatches. So `join`ing on metamaps seems to be a bad idea. We could either just not merge on meta maps and extract the `id` anywhere we need to join. Although the issue seems to occur in particular with mutect2 (& deepvariant), so it may be just something in that subworkflow. Extracting the `id`s also seem to have some pitfalls, which makes me think that really something else is also going on
For the detailed discussion also see: https://nfcore.slack.com/archives/CGFUX04HZ/p1677742801147389

**Comment by BrunoGrandePhD** [comment]
Just as an update, I was going to work on debugging this bug, but I'm no longer able to reproduce it. We had to clear the cache because it was too expensive, so I ran a subset of the sample through the MuTect2 variant calling, and the `FILTERMUTECTCALLS` step ran 13 times as expected. I'll keep my eyes peeled for this issue, and when it does, I'll resume my debugging work. 

![image](https://user-images.githubusercontent.com/740725/229819803-18827396-0c30-457a-ac37-454021a18cff.png)

**Comment by FriederikeHanssen** [comment]
We have made a lot of changes since the most recent release (3.2.1), that hsould have fixed all those and testing looked good. I iwll close this now, but if anyone re-experiences this issue then please re-open. It may look slightly different now. A lot of fail safes were added to prevent joining on mismatching files. So a typical error message would look something like this:

```
Join mismatch for the following entries: key=[patient:test, sample:test, sex:XX, status:0, id:test, data_type:bam] values=
```
